In [1]:
from scipy import stats
import numpy as np
import pandas as pd

In [2]:
dataFrame = pd.read_csv('dataset_correlacao.csv')
dataFrame.head()

Faturamento  Pontos
0        688.6      80
1        543.0      72
2        466.9      44
3        424.5      63
4        402.0      66

In [3]:
print(len(dataFrame))

20


In [4]:
stats.kstest(dataFrame['Pontos'],'norm')

KstestResult(statistic=1.0, pvalue=0.0)

In [5]:
statistic, pvalue = stats.kstest(dataFrame['Pontos'],'norm')
if pvalue> 0.29407:
    print('Não é uma disttribuição')
else:
    print('É uma distribuição normal')

É uma distribuição normal


# SW


In [7]:
print(stats.shapiro(dataFrame['Pontos']))
if stats.shapiro(dataFrame['Pontos'])[1]> 0.05:
    print('Distribuição Normal')
else:
    print('Não é uma Distribuição Normal')

ShapiroResult(statistic=0.9667134284973145, pvalue=0.6845294833183289)
Distribuição Normal


In [10]:
dataFrame = pd.read_csv('premier_league.csv')
dataFrame.head()

team  pos.  wins  losses  draws  pts  goals  total_pass  \
0  Manchester United     1    28       5      5   89     83       18723   
1            Chelsea     2    24       3     11   83     64       16759   
2          Liverpool     3    20      10      8   68     57       17154   
3            Arsenal     4    19       8     11   68     63       18458   
4  Tottenham Hotspur     5    17      12      9   60     57       14914   

      season  
0  2006-2007  
1  2006-2007  
2  2006-2007  
3  2006-2007  
4  2006-2007

In [11]:
dataFrame['pts'].describe()

count     60.000000
mean      76.600000
std        9.158121
min       58.000000
25%       70.000000
50%       75.500000
75%       84.250000
max      100.000000
Name: pts, dtype: float64

In [13]:
dataFrame['pts'][dataFrame['pts'] == 58]= 120

C:\Users\vitor.50220\AppData\Local\Temp\ipykernel_13324\3902405387.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame['pts'][dataFrame['pts'] == 58]= 120


In [14]:
dataFrame['pts'].describe()

count     60.000000
mean      77.633333
std       10.432944
min       60.000000
25%       70.000000
50%       76.000000
75%       85.000000
max      120.000000
Name: pts, dtype: float64

In [15]:
dataFrame['pts'][dataFrame['pts']>107.5]= 107.5

C:\Users\vitor.50220\AppData\Local\Temp\ipykernel_13324\1914931524.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFrame['pts'][dataFrame['pts']>107.5]= 107.5


In [17]:
dataFrame['pts'].describe()

count     60.000000
mean      77.425000
std        9.669463
min       60.000000
25%       70.000000
50%       76.000000
75%       85.000000
max      107.500000
Name: pts, dtype: float64

In [18]:
dataFrame['pts'][dataFrame['pts']<47.5]= 47.5

### Box-cox

In [22]:
ponto_novo, lambda_boxcox = stats.boxcox(dataFrame['pts'])

In [23]:
ponto_novo

array([1.26976964, 1.26742297, 1.25999132, 1.25999132, 1.25471408,
       1.26901913, 1.26823759, 1.26742297, 1.26427679, 1.25814664,
       1.27013386, 1.26863236, 1.26742297, 1.26223893, 1.2561456 ,
       1.26863236, 1.26823759, 1.2637853 , 1.26114341, 1.25683125,
       1.26613403, 1.26169797, 1.26169797, 1.25999132, 1.27552787,
       1.26976964, 1.26976964, 1.26114341, 1.26057472, 1.25814664,
       1.26976964, 1.26522639, 1.2637853 , 1.26276682, 1.26223893,
       1.26863236, 1.26783455, 1.26700256, 1.26568527, 1.26223893,
       1.26901913, 1.26568527, 1.2637853 , 1.26114341, 1.257498  ,
       1.26657302, 1.26169797, 1.25877794, 1.25877794, 1.26114341,
       1.27118499, 1.26863236, 1.2637853 , 1.26522639, 1.26427679,
       1.27342007, 1.26657302, 1.26475702, 1.26114341, 1.2637853 ])

In [24]:
print(stats.shapiro(ponto_novo))

ShapiroResult(statistic=0.9853790402412415, pvalue=0.6897542476654053)


In [25]:
print(stats.shapiro(dataFrame['pts']))

ShapiroResult(statistic=0.9676477313041687, pvalue=0.11184413731098175)


In [26]:
from scipy.special import inv_boxcox

In [27]:
ponto_velho = inv_boxcox(ponto_novo, lambda_boxcox)

In [29]:
ponto_velho

array([ 89. ,  83. ,  68. ,  68. ,  60. ,  87. ,  85. ,  83. ,  76. ,
        65. ,  90. ,  86. ,  83. ,  72. ,  62. ,  86. ,  85. ,  75. ,
        70. ,  63. ,  80. ,  71. ,  71. ,  68. , 107.5,  89. ,  89. ,
        70. ,  69. ,  65. ,  89. ,  78. ,  75. ,  73. ,  72. ,  86. ,
        84. ,  82. ,  79. ,  72. ,  87. ,  79. ,  75. ,  70. ,  64. ,
        81. ,  71. ,  66. ,  66. ,  70. ,  93. ,  86. ,  75. ,  78. ,
        76. , 100. ,  81. ,  77. ,  70. ,  75. ])

### box cox-2


In [6]:
ponto_novo, lambda_boxcox = stats.boxcox(dataFrame['Pontos'])

In [7]:
ponto_novo

array([28.54691059, 26.43765262, 18.3840581 , 23.97621215, 24.80803849,
       21.10995435, 18.69489133, 25.62830077, 18.07104212, 22.84785505,
       20.21842339, 22.27487863, 20.51738474, 19.61491134, 17.75577677,
       11.21149601, 16.14310198, 18.3840581 , 17.11821268, 18.3840581 ])

In [14]:
print(stats.shapiro(ponto_novo))

ShapiroResult(statistic=0.9685488939285278, pvalue=0.7239810228347778)


In [10]:
print(stats.shapiro(dataFrame['Pontos']))

ShapiroResult(statistic=0.9667134284973145, pvalue=0.6845294833183289)


In [9]:
from scipy.special import inv_boxcox

In [11]:
ponto_velho = inv_boxcox(ponto_novo, lambda_boxcox)

In [12]:
ponto_velho

array([80., 72., 44., 63., 66., 53., 45., 69., 43., 59., 50., 57., 51.,
       48., 42., 23., 37., 44., 40., 44.])